class RoomsModel {
  String name, date;
  RoomsModel({required this.name, required this.date});
}

List<RoomsModel> rooms = [
  RoomsModel(name: "K5 Bois🏏", date: "Oct 6"),
  RoomsModel(name: "Squarred rainbow🌈", date: "Sep 18"),
  RoomsModel(name: "Fab5", date: "Sep 16"),
  RoomsModel(name: "CSE updates💻👩‍💻👨‍💻", date: "Sep 14"),
  RoomsModel(name: "School buddies🏫", date: "Sep 10"),
  RoomsModel(name: "Flutter mahaDEVs📱", date: "Sep 12"),
  RoomsModel(name: "Placement cell👨‍🎓", date: "Sep 10"),
  RoomsModel(name: "Vikings🎥", date: "Sep 08"),
  RoomsModel(name: "Stories🛌😴", date: "Sep 18"),
  RoomsModel(name: "Redukt", date: "Sep 07"),
  RoomsModel(name: "Fake frnds🐕", date: "Sep 02"),
  RoomsModel(name: "K5 Bois🏏", date: "Oct 6"),
  RoomsModel(name: "Squarred rainbow🌈", date: "Sep 18"),
  RoomsModel(name: "Fab5", date: "Sep 16"),
  RoomsModel(name: "CSE updates💻👩‍💻👨‍💻", date: "Sep 14"),
  RoomsModel(name: "School buddies🏫", date: "Sep 10"),
  RoomsModel(name: "Flutter mahaDEVs📱", date: "Sep 12"),
  RoomsModel(name: "Placement cell👨‍🎓", date: "Sep 10"),
  RoomsModel(name: "Vikings🎥", date: "Sep 08"),
  RoomsModel(name: "Stories🛌😴", date: "Sep 18"),
  RoomsModel(name: "Redukt", date: "Sep 07"),
  RoomsModel(name: "Fake frnds🐕", date: "Sep 02"),
  RoomsModel(name: "K5 Bois🏏", date: "Oct 6"),
  RoomsModel(name: "Squarred rainbow🌈", date: "Sep 18"),
  RoomsModel(name: "Fab5", date: "Sep 16"),
  RoomsModel(name: "CSE updates💻👩‍💻👨‍💻", date: "Sep 14"),
  RoomsModel(name: "School buddies🏫", date: "Sep 10"),
  RoomsModel(name: "Flutter mahaDEVs📱", date: "Sep 12"),
  RoomsModel(name: "Placement cell👨‍🎓", date: "Sep 10"),
  RoomsModel(name: "Vikings🎥", date: "Sep 08"),
  RoomsModel(name: "Stories🛌😴", date: "Sep 18"),
  RoomsModel(name: "Redukt", date: "Sep 07"),
  RoomsModel(name: "Fake frnds🐕", date: "Sep 02"),
];
